### ISSUE TITLE
kubenetes resources bug

### ISSUE THREAD

**Issue by pindge** [GeoscienceAustralia/dea-airflow#135]
Multiple of our dags when running `airflow list_dags` is returning error

```
[2020-11-16 23:59:55,417] {dagbag.py:259} ERROR - Failed to import: /opt/airflow/dags/dags/sentinel_2_nrt/utility_ows_update_extent.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/sentinel_2_nrt/utility_ows_update_extent.py", line 96, in <module>
    SET_REFRESH_PRODUCT_TASK_NAME,
  File "/opt/airflow/dags/dags/sentinel_2_nrt/subdag_ows_views.py", line 127, in ows_update_extent_subdag
    dag=dag_subdag,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 98, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 213, in __init__
    self.resources = self._set_resources(resources)
TypeError: _set_resources() takes 1 positional argument but 2 were given
```

the temp solution is follow and needs to be rechecked when airflow base version is upgrade

When we upgrade airflow version, this will be updated.
```
# this is a hack
# as of airflow 1.10.11, setting resources key seems to have a bug
# https://github.com/apache/airflow/issues/9827
# it adds superfluous keys to the specs with nulls as values and k8s does not like that
# it probably was fixed here: https://github.com/apache/airflow/pull/10084
# once we upgrade airflow, this hack will not be need anymore

class PatchedResources(Resources):
    def to_k8s_client_obj(self):
        result = dict(requests={}, limits={})

        if self.request_memory is not None:
            result["requests"]["memory"] = self.request_memory
        if self.request_cpu is not None:
            result["requests"]["cpu"] = self.request_cpu

        if self.limit_memory is not None:
            result["limits"]["memory"] = self.limit_memory
        if self.limit_cpu is not None:
            result["limits"]["cpu"] = self.limit_cpu

        return k8s.V1ResourceRequirements(**result)

```

**Comment by pindge** [comment]
fixed in https://github.com/GeoscienceAustralia/dea-airflow/commit/efb3686d454df52d81b630c39c771f959e61c416
